---
collections:
  - name: redhat.openshift
    version: 4.0.1
  - name: redhat.openshift_virtualization
    version: 2.1.0
  - name: infra.middleware_ocpv
    version: 1.0.0
  - name: kubernetes.core
    version: 5.1.0
  - name: ansible.posix
    version: 1.6.2
  - name: ansible.utils
    version: 5.1.2
