---
- name: Openshift stuff
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Get a list of all VirtualMachines
      register: vm_list
      redhat.openshift_virtualization.kubevirt_vm_info:
        namespace: vmexamples-user1

    - name: Print out my list
      ansible.builtin.debug:
        var: vm_list

    - name: Get Cluster information
      register: api_status
      kubernetes.core.k8s_cluster_info:

    - name: Print out my api_status
      ansible.builtin.debug:
        var: api_status

    - name: Create a VirtualMachine
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        name: testvm
        namespace: vmexamples-user1
        labels:
          app: test
        instancetype:
          name: u1.medium
        preference:
          name: fedora
        spec:
          domain:
            devices:
              interfaces:
                - name: default
                  masquerade: {}
                - name: bridge-network
                  bridge: {}
          networks:
            - name: default
              pod: {}
            - name: bridge-network
              multus:
                networkName: kindexgw
          volumes:
            - containerDisk:
                image: quay.io/containerdisks/fedora:latest
              name: containerdisk
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  # The default username is: fedora
                  ssh_authorized_keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5zwKjGiBZ4ZkDIAgjfCxooqVPvJQd4LrJAm7PafkoLes59CdwNXH8+1flbEcVKNxfcRIMCdjx0pHuAosWNMVkq8R1SESddR4kxxKzeAtY3ws7xskrNhcRdhOXtNFvnTdkPLJ/ldfnfV4PXOhzfZx5uG022pAZlSBhubTTxZULLmeVSzrjpfhsAaCof5HKmurlNz8ijXCVNUNuT1hx3+k6rB73qYct58NwnFRpcxQY24UkmYUmfF80csegU20zOPL+vN8FPL+ITSDQwWgnjTKd2DRFtmG/pwfOH8Sc+DE6pFoQVueGHI84oeEodAy7tPqTuN8l9Oiurr9pZeFE3lG/5p+8BMGcEpPIqvje0B1zUqAPAVV5BBn4D5pfeyO/HQe5kPM6TMatZVfcmWQUWP4x/pDsuu5ECEAWcm5CUDAsdIInR5eFyLdTeXXjj7lLQkiUS+e2yiFTkEqLpE9uiNChNhiMuYYeSnvE2uqlK/2GVp5vBYbojQzhgyaofdFVXtM= eames@eames.remote.csb
              name: cloudinit
